version: 2
updates:
- package-ecosystem: npm
  directory: "/services/backend"
  schedule:
    interval: daily
  open-pull-requests-limit: 16
  assignees:
  - DominicRoyStang
- package-ecosystem: npm
  directory: "/services/frontend"
  schedule:
    interval: weekly
  open-pull-requests-limit: 16
  assignees:
  - DominicRoyStang
- package-ecosystem: npm
  directory: "/services/website"
  schedule:
    interval: weekly
  open-pull-requests-limit: 16
  assignees:
  - DominicRoyStang
