steps:
    - id: "Build backend"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA", "./services/backend"]
      waitFor: ["-"]

    - id: "Build frontend"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME:$SHORT_SHA", "./services/frontend"]
      waitFor: ["-"]

    - id: "Push built backend image to registry"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME"]
      waitFor: ["Build backend"]

    - id: "Push built frontend image to registry"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME"]
      waitFor: ["Build frontend"]

    - id: "Frontend tests"
      name: "gcr.io/cloud-builders/docker"
      args: ["run", "gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME:$SHORT_SHA", "npm", "run", "test"]
      waitFor: ["Build frontend"]

    - id: "Promote backend image to latest"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: "bash"
      args:
        - '-c'
        - |
          [[ "$BRANCH_NAME" == "master" ]] && gcloud container images add-tag gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:latest || echo "skipping..."

    - id: "Promote frontend image to latest"
      name: "gcr.io/cloud-builders/gcloud"
      entrypoint: "bash"
      args:
        - '-c'
        - |
          [[ "$BRANCH_NAME" == "master" ]] && gcloud container images add-tag gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME:latest || echo "skipping..."

substitutions:
    _BACKEND_SERVICE_NAME: "" # default value
    _FRONTEND_SERVICE_NAME: "" # default value
timeout: 1800s
