steps:
    - id: 'Build images'
      name: 'docker/compose:1.24.1'
      args: ['--file', 'services/docker-compose.yaml', 'build', '--parallel']
      waitFor: ['-']

    # Run containers in the background
    - id: 'Run containers'
      name: 'docker/compose:1.24.1'
      args: ['--file', 'services/docker-compose.yaml', 'up', '--detach']

    - id: 'Backend tests'
      name: 'docker/compose:1.24.1'
      args: ['--file', 'services/docker-compose.yaml', 'exec', '-T', 'backend', 'npm', 'run', 'test']
      waitFor: ['Run containers']

    - id: 'Frontend tests'
      name: 'docker/compose:1.24.1'
      args: ['--file', 'services/docker-compose.yaml', 'exec', '-T', 'frontend', 'npm', 'run', 'test']
      waitFor: ['Run containers']

    - id: 'Tag backend image'
      name: 'gcr.io/cloud-builders/docker'
      args: ['tag', 'backend:latest', 'gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA']
      waitFor: ['Build images']

    - id: 'Tag frontend image'
      name: 'gcr.io/cloud-builders/docker'
      args: ['tag', 'frontend:latest', 'gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME:$SHORT_SHA']
      waitFor: ['Build images']

    - id: 'Push backend image to registry'
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME']
      waitFor: ['Tag backend image']

    - id: 'Push frontend image to registry'
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME']
      waitFor: ['Tag frontend image']

    - id: 'Promote backend image to latest'
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          [[ "$BRANCH_NAME" == "master" ]] && gcloud container images add-tag gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:latest || echo "skipping..."

    - id: 'Promote frontend image to latest'
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          [[ "$BRANCH_NAME" == "master" ]] && gcloud container images add-tag gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$_FRONTEND_SERVICE_NAME:latest || echo "skipping..."

substitutions:
    _BACKEND_SERVICE_NAME: '' # default value
    _FRONTEND_SERVICE_NAME: '' # default value

timeout: 1800s
