{{$label := .Values.database.label}}
{{$secrets := .Values.database.secrets}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$label}}-deployment
  labels:
    app: {{$label}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{$label}}
  template:
    metadata:
      labels:
        app: {{$label}}
    spec:
      containers:
      - name: postgres
        image: {{.Values.database.image}}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: {{$label}}-pod-volume
          mountPath: '/var/lib/postgresql/data'
          subPath: postgres
        env:
        - name: POSTGRES_DB
          value: {{$secrets.database_name}}
        - name: POSTGRES_USER
          value: {{$secrets.database_user}}
        - name: POSTGRES_PASSWORD
          value: {{$secrets.database_password}}
      volumes:
      - name: {{$label}}-pod-volume
        persistentVolumeClaim:
          claimName: {{$label}}-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: {{$label}}-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{$label}}
  ports:
  - port: {{$secrets.database_port}}
    targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$label}}-volume-claim
  namespace: {{.Values.namespace}}
  labels:
    app: {{$label}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
