{{$label := .Values.frontend.label}}
{{$secrets := .Values.frontend.secrets}}
{{$backend_secrets := .Values.backend.secrets}}

apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{$label}}-deployment
    labels:
        app: {{$label}}
    namespace: {{.Values.namespace}}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{$label}}
    template:
        metadata:
            labels:
                app: {{$label}}
        spec:
            containers:
              - name: frontend
                image: {{.Values.frontend.image}}
                imagePullPolicy: IfNotPresent
                ports:
                  - containerPort: 3001
                env:
                  - name: REACT_APP_BACKEND_PROTOCOL
                    value: {{.Values.backend.protocol}}
                  - name: REACT_APP_BACKEND_HOST
                    value: {{.Values.backend.host}}
                  - name: REACT_APP_BACKEND_PORT
                    value: {{.Values.backend.port | squote}}

---

apiVersion: v1
kind: Service
metadata:
    name: {{$label}}-service
    namespace: {{.Values.namespace}}
spec:
    type: NodePort
    selector:
        app: {{$label}}
    ports:
      - port: {{.Values.frontend.port}}
        targetPort: 3001
