apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: blockedtodo-ingress
    annotations:
        kubernetes.io/ingress.class: gce
        kubernetes.io/ingress.global-static-ip-name: {{.Values.static_ip_name}}
        networking.gke.io/managed-certificates: blockedtodo-certificate
        networking.gke.io/v1beta1.FrontendConfig: ingress-security-config
    namespace: {{.Values.namespace}}
spec:
    rules:
      - host: {{.Values.backend.host}}
        http:
            paths:
              - backend:
                    serviceName: backend-service
                    servicePort: {{.Values.backend.port}}
      - host: www.{{.Values.backend.host}}
        http:
            paths:
              - backend:
                    serviceName: backend-service
                    servicePort: {{.Values.backend.port}}

      - host: {{.Values.frontend.host}}
        http:
            paths:
              - backend:
                    serviceName: frontend-service
                    servicePort: {{.Values.frontend.port}}
      - host: www.{{.Values.frontend.host}}
        http:
            paths:
              - backend:
                    serviceName: frontend-service
                    servicePort: {{.Values.frontend.port}}

      - host: {{.Values.website.host}}
        http:
            paths:
              - backend:
                    serviceName: website-service
                    servicePort: {{.Values.website.port}}
      - host: www.{{.Values.website.host}}
        http:
            paths:
              - backend:
                    serviceName: website-service
                    servicePort: {{.Values.website.port}}

---

# For HTTPS, as per https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs
{{- if eq .Values.environment "production"}}
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
    name: blockedtodo-certificate
    namespace: {{.Values.namespace}}
spec:
    domains:
        - {{.Values.backend.host}}
        - www.{{.Values.backend.host}}
        - {{.Values.frontend.host}}
        - www.{{.Values.frontend.host}}
        - {{.Values.website.host}}
        - www.{{.Values.website.host}}
{{- end}}

---

# For HTTP to HTTPS redirects, as per https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect
# Following this recipe: https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/ingress/secure-ingress
{{- if eq .Values.environment "production"}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
    name: ingress-security-config
spec:
    sslPolicy: gke-ingress-ssl-policy
    redirectToHttps:
        enabled: true
{{- end}}
