version: '3.7'

services:
  backend:
    image: backend
    stdin_open: true
    tty: true
    depends_on:
      - database
    build:
      context: ./backend
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
      - backend-node-modules:/backend/node_modules

  database:
    image: postgres:12.2
    environment:
        POSTGRES_DB: app-database
        POSTGRES_USER: app-database-user
        POSTGRES_PASSWORD: app-database-password
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  backend-node-modules:
  database-data:
