version: '3.7'

services:
    frontend:
        image: frontend
        stdin_open: true
        depends_on:
            - database
            - backend
        build:
            context: ./frontend
        environment:
            - REACT_APP_BACKEND_HOST=backend
            - REACT_APP_BACKEND_PORT=3001
        command: sh ./scripts/docker-start-dev.sh
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/frontend
            - frontend-node-modules:/frontend/node_modules

    backend:
        image: backend
        stdin_open: true
        tty: true
        depends_on:
            - database
        build:
            context: ./backend
        environment:
            - DATABASE_HOST=database
            - DATABASE_PORT=5432
            - DATABASE_NAME=app-database
            - DATABASE_USER=app-database-user
            - DATABASE_PASSWORD=app-database-password
            - TOKEN_SECRET=jwtsecret
        command: sh ./scripts/docker-start-dev.sh
        ports:
            - 3001:3001
            - 9222:9229 # Debugger port
        volumes:
            - ./backend:/backend
            - backend-node-modules:/backend/node_modules

    database:
        image: postgres:12.2
        environment:
            POSTGRES_DB: app-database
            POSTGRES_USER: app-database-user
            POSTGRES_PASSWORD: app-database-password
        ports:
            - 5432:5432
        volumes:
            - database-data:/var/lib/postgresql/data

volumes:
    frontend-node-modules:
    backend-node-modules:
    database-data:
