apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
    labels:
        app: backend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
              - name: backend
                image: backend:latest
                imagePullPolicy: IfNotPresent
                ports:
                  - containerPort: 3001
                env:
                  - name: TOKEN_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: backend-secret
                            key: token_secret
                  - name: GITHUB_WEBHOOKS_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: backend-secret
                            key: github_webhooks_secret
                  - name: GITHUB_APP_ID
                    valueFrom:
                        secretKeyRef:
                            name: backend-secret
                            key: github_app_id
                  - name: GITHUB_APP_PRIVATE_KEY
                    valueFrom:
                        secretKeyRef:
                            name: backend-secret
                            key: github_app_private_key
                  - name: DATABASE_NAME
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: database_name
                  - name: DATABASE_USER
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: database_user
                  - name: DATABASE_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: postgres-secret
                            key: database_password
                  - name: DATABASE_HOST
                    valueFrom:
                        configMapKeyRef:
                            name: postgres-configmap
                            key: database_host
                  - name: DATABASE_PORT
                    value: '5432'

---

apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    selector:
        app: backend
    type: LoadBalancer # Make it publicly accessible at the nodePort (give it an external IP address)
    ports:
      - port: 3001
        targetPort: 3001
        nodePort: 31234 # nodePort must be between 30000 & 32767
        protocol: TCP
