# Default values for blockedtodo.
# In a production environment, many of these values are overwritten.
# ie. either with the --set key1=val1,key2=val2 option or --values custom-values.yaml option

namespace: 'blockedtodo'

landing_page: 'blockedtodo.local'
static_ip_name: 'blockedtodo-ip'

database:
    label: 'postgres'
    image: 'postgres:12.2'
    secrets:
        database_port: '5432'
        database_name: 'app-database'
        database_user: 'app-database-user'
        database_password: 'app-database-password'

backend:
    label: 'backend'
    image: 'backend:latest'
    protocol: 'http'
    host: 'backend.blockedtodo.local'
    port: '80'
    secrets:
        token_secret: 'jwtsecret'
        github_webhooks_secret: 'overwrite'
        github_app_id: 'overwrite'
        github_app_private_key: 'overwrite'

frontend:
    label: 'frontend'
    image: 'frontend:latest'
    host: 'app.blockedtodo.local'
    port: '80'
